# Default file types to exclude
exclude_extensions:
  - ".jpg"
  - ".png"
  - ".exe"
  - ".bin"
  - ".pdf"

# Custom paths to skip
exclude_paths:
  - "node_modules/"
  - "vendor/"
  - "^\\."  # Exclude hidden files and directories

# Custom regex patterns (optional)
custom_patterns:
  - "foo_secret_[a-zA-Z0-9]{16}"
  - "some_other_custom_pattern"